### ISSUE TITLE
Installing the module fails

### ISSUE THREAD

**Issue by jmartsch** [MetaTunes/ProcessDbMigrate#1]
I downloaded the module via modules->install module via url and inserted the zip file from github https://github.com/MetaTunes/ProcessDbMigrate/archive/refs/heads/master.zip

The module is downloaded. Then I first installed FieldtypeRuntimeOnly and then ProcessDbMigrate.
Now the following error occurs:
You must assign a template to the page before setting custom field values

PW version is ProcessWire 3.0.173.

**Comment by MetaTunes** [comment]
Sorry about that @jmartsch  - I fixed it a couple of versions ago, but reintroduced it! Looking into it...

**Comment by MetaTunes** [comment]
OK @jmartsch - try v0.0.8 now. Let me know of any problems :)

**Comment by MetaTunes** [comment]
Whoah - hold on - one more fix!

**Comment by MetaTunes** [comment]
OK now - I hope!

**Comment by MetaTunes** [comment]
No!! - More downstream problems (bootstrapping tricky without tripping over!)

**Comment by MetaTunes** [comment]
Sorry about the blip - the fix didn't work with older PW versions. v0.0.9 should be OK to test now @jmartsch

**Comment by jmartsch** [comment]
Thanks. It installs now. Will test it out in the next days.
