### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by netcarver** [MetaTunes/ProcessDbMigrate#2]
@MetaTunes Hi Mark, thanks for this module, just started trying it out today and am seeing some strange layout issues in various pages in the admin interface after adding this.

Firstly, there are some layout issues with the module's initially shown page.
![2022-03-10_11-39](https://user-images.githubusercontent.com/16049/157654998-bc099b5f-0e76-4dfd-bac1-2dd79a285a65.png)

Then with the actual pages in the setup.
![2022-03-10_11-40](https://user-images.githubusercontent.com/16049/157655027-412fb9fe-3af7-4322-ac22-e15e6ad8de87.png)

And.
![2022-03-10_11-40_1](https://user-images.githubusercontent.com/16049/157655038-7e847431-406a-475c-ace6-4c55cd11d76b.png)

These start to impact other areas of the admin interface as well.
![2022-03-10_11-41](https://user-images.githubusercontent.com/16049/157655053-50dafd4e-6870-447c-b6aa-10299c3528be.png)

All resolve nicely once this module is uninstalled.

**Comment by MetaTunes** [comment]
Thanks @netcarver - I'll look into that but as mentioned in my other post, I will release a new version for you anyway (probably later this evening).

**Comment by netcarver** [comment]
No problem, thank you for your work on this.

**Comment by MetaTunes** [comment]
The rogue css is introduced by WireTabs. I don't know why. It was easily fixed (I hope) by adding css to my module - see v0.1.4.

**Comment by netcarver** [comment]
Yes, that seems to have cleared up the CSS issue - thank you.
